name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: gemini-test-427500

    - name: Authenticate to Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply --auto-approve
      run: terraform -chdir=terraform apply -auto-approve
      env:
        GOOGLE_CLOUD_PROJECT: gemini-test-427500
